config/routes.rb
Depot::Application.routes.draw do
  
  get 'admin' => 'admin#index'
  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end
  
  get "admin/index"

  get "sessions/new"

  get "sessions/create"

  get "sessions/destroy"

  resources :users

  resources :ussrs

  resources :orders

  resources :line_items

  resources :carts

  get "store/index"
  
  resources :products do
    get :who_bought, on: :member
  end

  root to: 'store#index', as: 'store'

end

app/models/ussr.rb
class Ussr < ActiveRecord::Base
  attr_accessible :name, :password_digest
  validates :name, presence: true, uniqueness: true
  has_secure_password
end

app/controllers/ussrs_controller.rb
class UssrsController < ApplicationController
  # GET /ussrs
  # GET /ussrs.json
  def index
    @ussrs = Ussr.order(:name)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @ussrs }
    end
  end

  # GET /ussrs/1
  # GET /ussrs/1.json
  def show
    @ussr = Ussr.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @ussr }
    end
  end

  # GET /ussrs/new
  # GET /ussrs/new.json
  def new
    @ussr = Ussr.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @ussr }
    end
  end

  # GET /ussrs/1/edit
  def edit
    @ussr = Ussr.find(params[:id])
  end

  # POST /ussrs
  # POST /ussrs.json
  def create
    @ussr = Ussr.new(params[:ussr])

    respond_to do |format|
      if @ussr.save
        format.html { redirect_to ussrs_url, notice: 'User #{@ussr.name} was successfully created.' }
        format.json { render json: @ussr, status: :created, location: @ussr }
      else
        format.html { render action: "new" }
        format.json { render json: @ussr.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /ussrs/1
  # PUT /ussrs/1.json
  def update
    @ussr = Ussr.find(params[:id])

    respond_to do |format|
      if @ussr.update_attributes(params[:ussr])
        format.html { redirect_to ussrs_url, notice: 'User #{@ussr.name} was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @ussr.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ussrs/1
  # DELETE /ussrs/1.json
  def destroy
    @ussr = Ussr.find(params[:id])
    @ussr.destroy

    respond_to do |format|
      format.html { redirect_to ussrs_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/ussrs_helper.rb
module UssrsHelper
end

app/views/ussrs/_form.html.haml
= form_for @ussr do |f|
  - if @ussr.errors.any?
    #error_explanation
      %h2
        = pluralize(@ussr.errors.count, "error")
        prohibited this user from being saved:
      %ul
        - @ussr.errors.full_messages.each do |msg|
          %li= msg
  %fieldset
    %legend Enter User Details
    %div
      = f.label :name
      \:
      \#{f.text_field :name, size: 40}
    %div
      = f.label :password, 'Password'
      \:
      \#{f.password_field :password, size: 40}
    %div
      = f.label :password_confirmation, 'Confirm'
      \:
      \#{f.password_field :password_confirmation, size: 40}
    %div
      = f.submit

app/views/ussrs/edit.html.haml
%h1 Editing ussr

= render 'form'

= link_to 'Show', @ussr
\|
= link_to 'Back', ussrs_path

app/views/ussrs/index.html.haml
%h1 Listing ussrs
- if notice
  %p#notice= notice

%table
  %tr
    %th Name
    %th Password digest
    %th
    %th
    %th

  - @ussrs.each do |ussr|
    %tr
      %td= ussr.name
      %td= ussr.password_digest
      %td= link_to 'Show', ussr
      %td= link_to 'Edit', edit_ussr_path(ussr)
      %td= link_to 'Destroy', ussr, :confirm => 'Are you sure?', :method => :delete

%br

= link_to 'New Ussr', new_ussr_path

app/views/ussrs/new.html.haml
%h1 New ussr

= render 'form'

= link_to 'Back', ussrs_path

app/views/ussrs/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @ussr.name
%p
  %b Password digest:
  = @ussr.password_digest

= link_to 'Edit', edit_ussr_path(@ussr)
\|
= link_to 'Back', ussrs_path